Default: &defaults
  database: sarah.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: sarah_test.sqlite3
  <<: *defaults

Staging:
  database: sarah_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: sarah_production.sqlite3
  poolsize: 100
  <<: *defaults
